Listen 8080
<VirtualHost *:8080>
    ServerName localhost
    DocumentRoot /Volumes/Storage/Workspace/WhatFUHaveDone

    <Directory /Volumes/Storage/Workspace/WhatFUHaveDone>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/worklog_error.log
    CustomLog ${APACHE_LOG_DIR}/worklog_access.log combined
</VirtualHost>
